import Config

# Configure your database
config :pad, Pad.Repo,
  username: "w",
  password: "1234",
  database: "etherpad",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

defmodule Watcher do
  def watch(modules, module, args) do
    modules
    |> Enum.map(fn m ->
      atom = String.to_atom("#{module}_#{Atom.to_string(m)}")
      {atom, {module, :install_and_run, [m, args]}}
    end)
  end
end

config :pad, PadWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4000],
  url: [host: "bc.grass.moe"],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Hw8UXgVrkdi06HPuW6NdJ4AA2AhgPVC/8Y3GSGVh0c9fIJWw+iKWXguoteOHoEAE",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:app, ~w(--sourcemap=inline --watch)]},
    dartsass:
      {DartSass, :install_and_run,
       [:app, ~w(--embed-source-map --source-map-urls=absolute --watch)]}
  ]

config :pad,
  api_key: ""

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :pad, PadWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/pad_web/(live|views)/.*(ex)$",
      ~r"lib/pad_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
