use Mix.Config

# Configure your database
config :pad, Pad.Repo,
  username: "w",
  password: "1234",
  database: "etherpad",
  hostname: "192.168.1.50",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

defmodule Watcher do
  def watch(modules, module, args) do
    modules
    |> Enum.map(fn m ->
      atom = String.to_atom("#{module}_#{Atom.to_string(m)}")
      {atom, {module, :install_and_run, [m, args]}}
    end)
  end
end

config :pad, PadWeb.Endpoint,
  url: [host: "w.grass.moe", port: 4006],
  http: [port: 4006],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers:
    Watcher.watch(
      [:app],
      Esbuild,
      ~w(--sourcemap=inline --watch)
    ) ++
      Watcher.watch(
        [:app],
        DartSass,
        ~w(--embed-source-map --source-map-urls=absolute --watch)
      )

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :pad, PadWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/pad_web/(live|views)/.*(ex)$",
      ~r"lib/pad_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
